[main]
verbose = true
no_delete = false
distro_name = "Linux"
options = [
    "quiet",
    "rw"
]

[loader]
default = "linux"
timeout = 5
editor = false
auto_entries = true
auto_firmware = true
console_mode = "keep"
